name: smartsweep_precision
description: "An innovative Flutter app designed to control your Arduino Giga-based cleaning robot with utmost precision."
publish_to: 'none'
version: 1.0.1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.13
  flutter_markdown: ^0.6.19
  flutter_native_splash: ^2.3.9
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  package_info_plus: ^5.0.1
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  url_launcher: ^6.2.4
  wakelock_plus: ^1.1.4

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/anims/
    - assets/files/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_icon.png"
  web:
    generate: true
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#121212"
  android_12:
    color: "#ffffff"
    color_dark: "#121212"
